ENV['RACK_ENV'] ||= 'development'

require 'sinatra/base'
require 'sinatra/flash'
require 'sinatra/partial'
require 'rubygems'
require 'tilt/erb'
require 'byebug'
require 'haml'

require_relative 'data_mapper_setup'
require_relative 'server'
require_relative 'controllers/users'
require_relative 'controllers/chits'
require_relative 'controllers/replies'
require_relative 'controllers/sessions'
